### ISSUE TITLE
Usage questions

### ISSUE THREAD

**Issue by bard** [Banou26/parcel-plugin-babel-typescript#1]
Thanks for sharing this plugin. A couple of questions:

1. Is anything needed in `.babelrc` to make use of it (e.g. `"presets": ["@babel/typescript"]`)?
2. Are `tsx` files processed?

I'm asking because everything seems to be working in my testcase, but I can't tell if that's because of parcel's default processing or the plugin's.

**Comment by Banou26** [comment]
No, you don't have to do anything in addition of installing the plugin, that's the magic of parcel.
If you wanna know if everything worked, you can try installing a proposal like `@babel/plugin-proposal-optional-chaining` and use it to see if it works.
This normally wouldn't work with Parcel's default processing.
I didn't register the `.tsx` files as registered by the plugin, would you want me to ?
I never used JSX so i don't really know if it'd work directly or not.

**Comment by Banou26** [comment]
The only thing you need to add in addition of installing my plugin is, installing a babel proposal(e.g `@babel/plugin-proposal-optional-chaining`) and add its configuration in the babel config file e.g
.babelrc
```js
{
  "plugins": [
    "@babel/plugin-proposal-optional-chaining"
  ]
}
```
If you can then use features from the proposal like `undefined?.foo` without it throwing an error, it worked.
This normally wouldn't work with Parcel's default typescript processing.

I didn't register `.tsx` files as registered by the plugin, would you want me to ?
I never used JSX so i don't really know if it'd work directly or not.

**Comment by bard** [comment]
Could you please have a look at [this repro](https://github.com/bard/repro-parcel-babel-typescript)?

If `.babelrc` is only:

```
{
  "plugins": [
    "@babel/plugin-proposal-optional-chaining"
  ]
}
```

Then TypeScript annotations aren't stripped, causing this error:

```
index.ts:2:7: Unexpected token (2:7)
  1 | 
> 2 | const a: number = 3
    |       ^
  3 | 
```

However if `.babelrc` is:

```
{
  "presets": [
    "@babel/typescript"
  ],
  "plugins": [
    "@babel/plugin-proposal-optional-chaining"
  ]
}
```

It works.

I will do some testing with TSX (I assume only an extra call to `addAssetType` is needed in `index.js`) and report.

**Comment by Banou26** [comment]
Indeed, i actually myself have `@babel/preset-typescript` instead of `@babel/typescript` on my projects, I also didn't manage to find a `@babel/typescript` npm package but it seems to work nevertheless.

I should probably add a README.md informing about that.

https://stackoverflow.com/questions/34224007/is-there-any-downside-to-using-tsx-instead-of-ts-all-the-times-in-typescript
Seems to show that `.ts` and `.tsx` aren't compatible but `.tsx` users are used to not using casting like `<number>` but instead use `foo as number`.
So it seems i wouldn't have to do anything else than add the additional `addAssetType` call.

I'll add the changes right now.

**Comment by Banou26** [comment]
I pushed the changes.
Is there anything else you'd like to know or want from this plugin ?
If that is all, I'll let you close the issue.
And thank you for the questions/feedback !

**Comment by bard** [comment]
Indeed, there must be some implicit aliasing going on, I picked the `@babel/typescript` form for the preset right from the [official starter](https://github.com/Microsoft/TypeScript-Babel-Starter/blob/master/.babelrc).

True about `<type>name` vs `name as type`, now that you mention it I remember seeing it in the limitations of the babel-first approach in the [original announcement](https://devblogs.microsoft.com/typescript/typescript-and-babel-7/).

Thanks a lot for the quick response and again for sharing the work in the first place!
